### ISSUE TITLE
this project is harmful to humanity & should be stopped

### ISSUE THREAD

**Issue by rektide** [dessant/lock-threads-app#4]
this is bad software that does bad things to humanity.

rather than allow people to continue to gather knowledge & understand issues, it silences conversation & prevents further development.

this project should be deleted & disabled & apologies should be written. we should reflect & learn from our mistakes. (which is notably another thing lockbot does not allow us to do)

**Comment by dessant** [comment]
This topic has been discussed before, search this repository and dessant/lock-threads. The mental health and well-being of those who maintain popular open source projects will always come before your convenience.

I have to say the `apologies should be written` part is histerically funny, thanks for that.
